sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-full
script:
- make
deploy:
  provider: releases
  api_key:
    secure: TOKEN
  skip_cleanup: true
  file: English.pdf
  on:
    repo: suphero/cv
