sudo: false
language: generic
matrix:
  include:
  - os: linux
git:
  depth: false
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_install:
- bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- mkdir _build
- lualatex -interaction=nonstopmode -halt-on-error -output-directory _build English.tex
- lualatex -interaction=nonstopmode -halt-on-error -output-directory _build Turkish.tex