version: 2

jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Make Build Directory
          command: mkdir build
      - run:
          name: Compile
          command: make
      - store_artifacts:
          path: build
