version: 2.1
jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Make Build Directory
          command: mkdir build
      - run:
          name: Make PDFs
          command: |
            make english.pdf
            make turkish.pdf
      - run:
          name: Move artifacts
          command: |
            mkdir -p artifacts
            mv build/english.pdf artifacts
            mv build/turkish.pdf artifacts
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - artifacts
  publish:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=1.0.0
            ghr -t "${GITHUB_TOKEN}" -u "${CIRCLE_PROJECT_USERNAME}" -r "${CIRCLE_PROJECT_REPONAME}" -c "${CIRCLE_SHA1}" -delete "${VERSION}" artifacts
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
