version: 2.1
jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install -y git
      - run:
          name: Make Build Directory
          command: mkdir build
      - run:
          name: Compile
          command: make
      - store_artifacts:
          path: build
  publish:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./build
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=1.0.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/
