version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6
jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Install git
          command: apt-get update && apt-get install -y git
      - run:
          name: Make Build Directory
          command: mkdir build
      - run:
          name: Compile
          command: make
      - store_artifacts:
          path: build
      - gh-pages/deploy:
          build-dir: build
          ssh-fingerprints: '54:42:2c:c7:3f:aa:88:48:88:ac:a7:49:2d:e0:eb:03'
