version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - store_artifacts:
          path: build2
      - persist_to_workspace:
          root: .
          paths:
            - build2
  publish:
    docker:
      - image: circleci/golang:latest
    steps:
      - attach_workspace:
          at: /tmp/build2
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=1.0.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build2/
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
