version: 2.1
jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install -y git golang
      - run:
          name: Install ghr
          command: go get -u github.com/tcnksm/ghr
      - run:
          name: Make Build Directory
          command: mkdir build
      - run:
          name: Compile
          command: make
      - store_artifacts:
          path: build
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=1.0.0
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./build/
